export AWS_ACCESS_KEY_ID=AKIAIB5TQBGYF4ZE2KEQ
export AWS_SECRET_ACCESS_KEY=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
export AWS_REGION=us-east-2
export S3_BUCKET=workhorseapp

#Stripe
export STRIPE_TEST_SECRET_KEY=sk_test_IScaci50UcG2PdCmkD7GYEgD
export STRIPE_TEST_PUBLISHABLE_KEY=pk_test_iusHghxtXvdlbzFIoTxCHdHc